# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build V8
        run: |
          docker run -d --privileged -v /tmp:/tmp -v ${PWD}:/build -h manjaro --name manjaro manjarolinux/base /usr/lib/systemd/systemd
          docker exec manjaro bash -c "pacman -Sy"
          docker exec manjaro bash -c "pacman --noconfirm -S pkg-config fakeroot sudo binutils gcc python gn ninja zlib icu patch"
          docker exec manjaro bash -c "useradd -U -m -s /bin/bash builder"
          docker exec manjaro bash -c "chown -R builder:builder /build"
          docker exec manjaro bash -c "cd /build/v8; sudo -u builder makepkg"
          docker exec manjaro bash -c "cd /build/v8; sudo -u builder repo-add aeongames.db.tar.xz v8-8.8.278.14-1-any.pkg.tar.zst"
          docker stop manjaro
          docker container prune -f
